import java.awt.Image;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Katherin
 */
public class ParcialKatherin extends javax.swing.JFrame {

    /**
     * Creates new form ParcialKatherin
     */
    public ParcialKatherin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        label_ciudad = new javax.swing.JLabel();
        label_valor = new javax.swing.JLabel();
        label_peso = new javax.swing.JLabel();
        texto_ciudad = new javax.swing.JTextField();
        texto_valor = new javax.swing.JTextField();
        texto_peso = new javax.swing.JTextField();
        label_kg = new javax.swing.JLabel();
        boton_validar = new javax.swing.JButton();
        boton_salir = new javax.swing.JButton();
        label_resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        label_ciudad.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        label_ciudad.setText("CIUDAD");

        label_valor.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        label_valor.setText("VALOR");

        label_peso.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        label_peso.setText("PESO");

        texto_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_ciudadActionPerformed(evt);
            }
        });

        texto_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_valorActionPerformed(evt);
            }
        });

        texto_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_pesoActionPerformed(evt);
            }
        });

        label_kg.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        label_kg.setText("KG");

        boton_validar.setText("VALIDAR");
        boton_validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_validarActionPerformed(evt);
            }
        });

        boton_salir.setText("SALIR");
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });

        label_resultado.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        label_resultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label_ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_peso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(boton_validar)
                                    .addComponent(texto_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_kg)
                                .addGap(48, 48, 48)
                                .addComponent(boton_salir)))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ciudad)
                    .addComponent(texto_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_valor)
                    .addComponent(texto_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_peso)
                            .addComponent(texto_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_kg))
                        .addGap(18, 18, 18)
                        .addComponent(boton_validar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(boton_salir)))
                .addGap(26, 26, 26)
                .addComponent(label_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_ciudadActionPerformed

    private void texto_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_valorActionPerformed
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
        return retValue;
    }
    private void texto_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_pesoActionPerformed

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        dispose();
    }//GEN-LAST:event_boton_salirActionPerformed

    private void boton_validarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_validarActionPerformed
        // TODO add your handling code here:
        if (texto_ciudad.getText().equals("") || texto_valor.getText().equals("") || texto_peso.getText().equals("")) {
            label_resultado.setText("Faltan Datos");
        } else {
            label_resultado.setText("El valor del envío por " + texto_valor.getText() + ",<br> de la ciudad de " + texto_ciudad.getText() + ",\n tiene un peso de " + texto_peso.getText() + label_kg.getText());
        }
    }//GEN-LAST:event_boton_validarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParcialKatherin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParcialKatherin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParcialKatherin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParcialKatherin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParcialKatherin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_salir;
    private javax.swing.JButton boton_validar;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel label_ciudad;
    private javax.swing.JLabel label_kg;
    private javax.swing.JLabel label_peso;
    private javax.swing.JLabel label_resultado;
    private javax.swing.JLabel label_valor;
    private javax.swing.JTextField texto_ciudad;
    private javax.swing.JTextField texto_peso;
    private javax.swing.JTextField texto_valor;
    // End of variables declaration//GEN-END:variables
}
